"""orders, vendor users, po key

Revision ID: c2ded11b0196
Revises: fa4fbb44aa4c
Create Date: 2026-07-29 13:55:53.243642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ded11b0196'
down_revision: Union[str, Sequence[str], None] = 'fa4fbb44aa4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('vendor_org_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_salt', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_org_id'], ['vendor_orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=True),
    sa.Column('sap_po_number', sa.String(length=35), nullable=False),
    sa.Column('sap_po_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('received', 'acknowledged', 'shipped', 'delivered', 'cancelled', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ordered_at', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_payload_key', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sap_po_number')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('vendor_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('vendor_user_id', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('order_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    op.create_table('order_lines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('supplier_part_id', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('item_id', sa.String(length=32), nullable=True),
    sa.Column('contract_id', sa.String(length=32), nullable=True),
    sa.Column('expected_unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('price_verdict', sa.Enum('match', 'overpaid', 'underpaid', 'off_catalog', name='priceverdict', native_enum=False), nullable=True),
    sa.Column('price_delta', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_key_hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('vendor_orgs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_orgs', schema=None) as batch_op:
        batch_op.drop_column('invite_code_hash')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('po_key_hash')

    op.drop_table('order_lines')
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))

    op.drop_table('order_events')
    op.drop_table('vendor_tokens')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    op.drop_table('vendor_users')
    # ### end Alembic commands ###
