"""initial schema

Revision ID: fa4fbb44aa4c
Revises: 
Create Date: 2026-07-29 13:33:27.511770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4fbb44aa4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_orgs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'dead', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('policy_evaluations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('cart_ref', sa.String(length=120), nullable=True),
    sa.Column('line_ref', sa.String(length=120), nullable=True),
    sa.Column('policy_id', sa.String(length=32), nullable=True),
    sa.Column('policy_version_no', sa.Integer(), nullable=True),
    sa.Column('fired_rules', sa.JSON(), nullable=True),
    sa.Column('evaluated_fields', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punchout_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('oci_version', sa.String(length=5), nullable=True),
    sa.Column('hook_url_encrypted', sa.Text(), nullable=True),
    sa.Column('buyer_cookie', sa.String(length=120), nullable=True),
    sa.Column('sap_user', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cart', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('vendor_org_id', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sap_vendor_no', sa.String(length=20), nullable=True),
    sa.Column('protocol', sa.Enum('cxml', 'oci', 'hosted', name='supplierprotocol', native_enum=False), nullable=False),
    sa.Column('punchout_url', sa.String(length=500), nullable=True),
    sa.Column('from_domain', sa.String(length=60), nullable=True),
    sa.Column('from_identity', sa.String(length=120), nullable=True),
    sa.Column('to_domain', sa.String(length=60), nullable=True),
    sa.Column('to_identity', sa.String(length=120), nullable=True),
    sa.Column('shared_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('deployment_mode', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('confirmed_mapping', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vendor_org_id'], ['vendor_orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_salt', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='userrole', native_enum=False), nullable=False),
    sa.Column('privileges', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email')
    )
    op.create_table('auth_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('catalog_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('loaded', 'published', 'superseded', name='versionstatus', native_enum=False), nullable=False),
    sa.Column('source_filename', sa.String(length=300), nullable=True),
    sa.Column('mapping_used', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=True),
    sa.Column('contract_no', sa.String(length=60), nullable=False),
    sa.Column('sap_agreement_no', sa.String(length=20), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('precedence', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'contract_no')
    )
    op.create_table('catalog_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('supplier_part_id', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=40), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('manufacturer_part_id', sa.String(length=120), nullable=True),
    sa.Column('uom_raw', sa.String(length=30), nullable=True),
    sa.Column('uom_sap', sa.String(length=10), nullable=True),
    sa.Column('unspsc', sa.String(length=12), nullable=True),
    sa.Column('material_group', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('price_unit', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('auto_approved', 'needs_review', 'manual', 'approved', 'rejected', name='itemstate', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_reasons', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('price_flags', sa.JSON(), nullable=True),
    sa.Column('raw_row', sa.JSON(), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['catalog_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'superseded', 'expired', name='policystatus', native_enum=False), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=True),
    sa.Column('requested_from', sa.Date(), nullable=False),
    sa.Column('requested_to', sa.Date(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('clamped', sa.Boolean(), nullable=False),
    sa.Column('clamp_note', sa.Text(), nullable=True),
    sa.Column('source_document', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('activated_by', sa.String(length=120), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('policy_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('action', sa.Enum('allow', 'warn', 'route_approval', 'block', name='policyaction', native_enum=False), nullable=False),
    sa.Column('route_to', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_clause', sa.String(length=120), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('draft_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_tiers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=True),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.Column('max_qty', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('price_unit', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_tiers')
    op.drop_table('policy_rules')
    op.drop_table('policies')
    op.drop_table('catalog_items')
    op.drop_table('contracts')
    op.drop_table('catalog_versions')
    op.drop_table('auth_tokens')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('punchout_sessions')
    op.drop_table('policy_evaluations')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))

    op.drop_table('jobs')
    op.drop_table('vendor_orgs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
