"""PO receipt — the endpoint S/4HANA output management pushes purchase orders
to. Mounted at /api/v1/po (versioned: Basis teams hard-code this URL).

Auth is a per-tenant integration key (X-PO-Key header), generated by a tenant
admin in the admin UI. Token-free bearer auth doesn't fit here because the
caller is a system, not a person. Production adds TLS + IP allowlisting on
top (GO-LIVE.md item 8).
"""

from __future__ import annotations

import hashlib
import hmac
import uuid

from fastapi import APIRouter, Depends, Header, HTTPException, Query, Request
from sqlalchemy.orm import Session

from ..db import get_db
from ..models import Tenant
from ..services import storage
from ..services.orders import PoError, parse_po_idoc, parse_po_json, receive_po

router = APIRouter()


def _authorized_tenant(db: Session, tenant_id: str, po_key: str | None) -> Tenant:
    tenant = db.get(Tenant, tenant_id)
    if tenant is None or not tenant.po_key_hash:
        # Same message either way: don't reveal which tenants exist.
        raise HTTPException(401, "Unknown tenant or PO key not configured")
    if not po_key or not hmac.compare_digest(
        hashlib.sha256(po_key.encode()).hexdigest(), tenant.po_key_hash
    ):
        raise HTTPException(401, "Wrong PO key")
    return tenant


@router.post("/receive")
async def receive(
    request: Request,
    tenant_id: str = Query(...),
    x_po_key: str | None = Header(None, alias="X-PO-Key"),
    po_key: str | None = Query(None),
    db: Session = Depends(get_db),
):
    """Accepts a PO as ORDERS05 IDoc-XML (Content-Type: application/xml or
    text/xml) or as JSON. Idempotent on (tenant, PO number): SAP re-pushes
    update the order in place and bump its version.

    The key is normally the X-PO-Key header; ?po_key= is accepted as a
    fallback because SAP's IDoc HTTP ports (SM59 type G) can set a URL but
    not custom headers."""
    tenant = _authorized_tenant(db, tenant_id, x_po_key or po_key)

    raw = await request.body()
    content_type = (request.headers.get("content-type") or "").lower()
    is_xml = "xml" in content_type or raw.lstrip()[:1] == b"<"

    try:
        if is_xml:
            parsed, source = parse_po_idoc(raw), "idoc"
        else:
            import json
            parsed, source = parse_po_json(json.loads(raw or b"{}")), "json"
    except PoError as e:
        raise HTTPException(422, str(e))
    except ValueError as e:  # json.JSONDecodeError
        raise HTTPException(422, f"Body is neither XML nor valid JSON: {e}")

    # Keep the exact payload SAP sent — disputes are settled with receipts.
    raw_key = storage.put(
        f"{tenant.id}/po-raw/{parsed['po_number']}-{uuid.uuid4().hex[:8]}"
        f".{'xml' if is_xml else 'json'}",
        raw,
    )

    order, created = receive_po(
        db, tenant.id, parsed, source=source, raw_payload_key=raw_key
    )
    return {
        "order_id": order.id,
        "sap_po_number": order.sap_po_number,
        "version": order.sap_po_version,
        "created": created,
        "status": order.status.value,
        "supplier_matched": order.supplier_id is not None,
        "lines": len(parsed["lines"]),
    }
